# Generated by Django 5.1.2 on 2025-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
